/*
  File autogenerated by gengetopt version 2.23
  generated with the following command:
  gengetopt --include-getopt --default-optional --unamed-opts -i options.ggo --string-parser -u

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif


#include "cmdline.h"

const char *gengetopt_args_info_purpose = "A versatile HTN planning";

const char *gengetopt_args_info_usage = "Usage: ./pandaPIengine [OPTIONS] input.sas";

const char *gengetopt_args_info_versiontext = "";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                    Print help and exit",
  "      --version                 Print version and exit",
  "\nGeneral Options:",
  "  -d, --debug                   activate debug mode",
  "  -S, --seed=INT                specify the random seed  (default=`42')",
  "  -t, --timelimit=INT           specify timelimit in seconds  (default=`1800')",
  "  -N, --noPlanOutput            don't output the plan [default=print plan]\n                                  (default=off)",
  "      --writeInputToHDDL        don't run the engine at all. Output the given\n                                  SAS+ planning problem as HDDL again.\n                                  (default=off)",
  "      --heuristicHelp           will print the help page for the heuristics\n                                  (default=off)",
  "\nPlanner Selection:",
  "  default=progression",
  "\n Group: planningAlgorithm",
  "  -p, --progression             progression search",
  "  -s, --sat                     translation to SAT",
  "  -b, --bdd                     symbolic search",
  "  -2, --translation             translation-based planner",
  "  -I, --interactive             interactive search",
  "\nProgression Search Options:",
  "  -H, --heuristic=STRING        specify heuristics. If you want to know how to\n                                  specify a heuristic, use --heuristicHelp. The\n                                  first heuristic in the list is the one used\n                                  for search. Starting from the second, all\n                                  other heuristics are used as tie-breakers. If\n                                  you specify the same heuristic twice, it will\n                                  only be computed once. If all tie-breakers\n                                  are equal, a random number selected per\n                                  search node is used as the final tie-breaker.\n                                  (default=`rc2(ff)')",
  "  -w, --astarweight=INT         weight of the heuristic for weighted A* (also\n                                  called greedy-A*). The default is 1, which\n                                  yields the standard A* algorithm.\n                                  (default=`1')",
  "  -g, --gValue=STRING           g value. You can select\n                                  path: one for each applied action and\n                                  performed decomposition\n                                  mixed: summed cost of the applied actions\n                                  plus 1 for every applied decomposition\n                                  action: summed cost of the applied actions\n                                  none: constant zero.\n                                    (possible values=\"path\", \"action\",\n                                  \"mixed\", \"none\" default=`path')",
  "      --suboptimal              suboptimal search (early goal test and visited\n                                  lists ignores costs)  (default=off)",
  "If you want to perform BFS, you need to run A* with the zero heuristic and\nselect the gValue as path.If you want to perform DFS, you need to run A* with\nthe inverted modDepth heuristic and select the gValue as none.Note that in both\ncases, we only simulate BFS and DFS using the standard sorted search queue,\nwhich incurs an additional log-time (in the size of the queue) factor.",
  "\nVisited List Options:",
  "  -V, --noVisitedList           disable visited lists [default=with lists]\n                                  (default=off)",
  "  -T, --noTaskHash              disable task hashing [default=with task hash]\n                                  (default=on)",
  "  -Q, --noTaskSequenceHash      disable task sequence hashing [default=with\n                                  task sequence hash]  (default=on)",
  "  -O, --noTopologicalOrdering   disable visited checking with task sequences,\n                                  this makes totally-ordered visited lists\n                                  incomplete [default=with order]  (default=on)",
  "      --noLayers                disable layer hashing [default=with layer hash]\n                                  (default=on)",
  "      --noOrderPairs            disable order pairs hashing [default=with order\n                                  pairs hash]  (default=on)",
  "      --noParallelSequences     disable optimisation for parallel sequences\n                                  [default=with optimisation]  (default=on)",
  "      --noGIcheck               disable GI-complete equivalence checking for\n                                  partially ordered task networks [default=with\n                                  GI-complete checking]  (default=on)",
  "\nSAT Planner Options:",
  "  -B, --blockcompression        apply block compression  (default=on)",
  "  -M, --satmutexes              encode SAT mutexes  (default=on)",
  "  -P, --pruning=STRING          pruning mode  (possible values=\"none\",\n                                  \"ff\", \"h2\" default=`ff')",
  "  -m, --methodPreconditionsInSeparateLeafs\n                                if in partial order mode, put method\n                                  precondition actions into extra leafs. This\n                                  allows for better encoding of executability,\n                                  but may increase the size of the PDT\n                                  (default=off)",
  "  -o, --optimisation            after finding the first plan, continue search\n                                  to find plans of lower cost  (default=on)",
  "\nTranslation Planner Options:",
  "      --downward=STRING         path to fast downward executable\n                                  (default=`none')",
  "      --downwardConf=STRING     configuration given to fast downward. This has\n                                  two special values that are expanded to\n                                  proper configurations. Use ehc-ff() for\n                                  enforced hill climbing with FF and lazy-cea()\n                                  for lazy-greedy search with the context\n                                  enhanced additive heuristic.\n                                  (default=`ehc-ff()')",
  "      --transtype=STRING        type of translation to use  (possible\n                                  values=\"push\", \"parallelseq\", \"to\",\n                                  \"postrips\", \"pocond\" default=`push')",
  "      --forceTransType          by default, pandaPIengine will switch to a\n                                  getter encoding if it detects the\n                                  prerequisites for it in the problem. This\n                                  flag disables this behaviour and always uses\n                                  the given encoding.  (default=off)",
  "      --sasfile=STRING          name of the SAS+ file generated. In planning\n                                  mode this file will be written and used as a\n                                  temporary file  (default=`output.sas')",
  "      --pgb=INT                 the initial value of the progression bound. If\n                                  zero, the minimum progression bound will be\n                                  computed and used instead. This is the\n                                  default behaviour!  (default=`0')",
  "      --pgbsteps=INT            step size of the progression bound\n                                  (default=`1')",
  "      --onlyGenerate            only generate the translation and don't solv\n                                  it. This overrides also iterate\n                                  (default=off)",
  "      --iterate                 if the initial pgb is unsolvable, increase by\n                                  one and continue  (default=off)",
  "      --realCosts               if enabled use the actual cost in the encoded\n                                  model. Default is off, then all operators\n                                  have unit cost.  (default=off)",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);
struct line_list
{
  char * string_arg;
  struct line_list * next;
};

static struct line_list *cmd_line_list = 0;
static struct line_list *cmd_line_list_tmp = 0;

static void
free_cmd_list(void)
{
  /* free the list of a previous call */
  if (cmd_line_list)
    {
      while (cmd_line_list) {
        cmd_line_list_tmp = cmd_line_list;
        cmd_line_list = cmd_line_list->next;
        free (cmd_line_list_tmp->string_arg);
        free (cmd_line_list_tmp);
      }
    }
}


const char *cmdline_parser_gValue_values[] = {"path", "action", "mixed", "none", 0}; /*< Possible values for gValue. */
const char *cmdline_parser_pruning_values[] = {"none", "ff", "h2", 0}; /*< Possible values for pruning. */
const char *cmdline_parser_transtype_values[] = {"push", "parallelseq", "to", "postrips", "pocond", 0}; /*< Possible values for transtype. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->debug_given = 0 ;
  args_info->seed_given = 0 ;
  args_info->timelimit_given = 0 ;
  args_info->noPlanOutput_given = 0 ;
  args_info->writeInputToHDDL_given = 0 ;
  args_info->heuristicHelp_given = 0 ;
  args_info->progression_given = 0 ;
  args_info->sat_given = 0 ;
  args_info->bdd_given = 0 ;
  args_info->translation_given = 0 ;
  args_info->interactive_given = 0 ;
  args_info->heuristic_given = 0 ;
  args_info->astarweight_given = 0 ;
  args_info->gValue_given = 0 ;
  args_info->suboptimal_given = 0 ;
  args_info->noVisitedList_given = 0 ;
  args_info->noTaskHash_given = 0 ;
  args_info->noTaskSequenceHash_given = 0 ;
  args_info->noTopologicalOrdering_given = 0 ;
  args_info->noLayers_given = 0 ;
  args_info->noOrderPairs_given = 0 ;
  args_info->noParallelSequences_given = 0 ;
  args_info->noGIcheck_given = 0 ;
  args_info->blockcompression_given = 0 ;
  args_info->satmutexes_given = 0 ;
  args_info->pruning_given = 0 ;
  args_info->methodPreconditionsInSeparateLeafs_given = 0 ;
  args_info->optimisation_given = 0 ;
  args_info->downward_given = 0 ;
  args_info->downwardConf_given = 0 ;
  args_info->transtype_given = 0 ;
  args_info->forceTransType_given = 0 ;
  args_info->sasfile_given = 0 ;
  args_info->pgb_given = 0 ;
  args_info->pgbsteps_given = 0 ;
  args_info->onlyGenerate_given = 0 ;
  args_info->iterate_given = 0 ;
  args_info->realCosts_given = 0 ;
  args_info->planningAlgorithm_group_counter = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->seed_arg = 42;
  args_info->seed_orig = NULL;
  args_info->timelimit_arg = 1800;
  args_info->timelimit_orig = NULL;
  args_info->noPlanOutput_flag = 0;
  args_info->writeInputToHDDL_flag = 0;
  args_info->heuristicHelp_flag = 0;
  args_info->heuristic_arg = NULL;
  args_info->heuristic_orig = NULL;
  args_info->astarweight_arg = 1;
  args_info->astarweight_orig = NULL;
  args_info->gValue_arg = gengetopt_strdup ("path");
  args_info->gValue_orig = NULL;
  args_info->suboptimal_flag = 0;
  args_info->noVisitedList_flag = 0;
  args_info->noTaskHash_flag = 1;
  args_info->noTaskSequenceHash_flag = 1;
  args_info->noTopologicalOrdering_flag = 1;
  args_info->noLayers_flag = 1;
  args_info->noOrderPairs_flag = 1;
  args_info->noParallelSequences_flag = 1;
  args_info->noGIcheck_flag = 1;
  args_info->blockcompression_flag = 1;
  args_info->satmutexes_flag = 1;
  args_info->pruning_arg = gengetopt_strdup ("ff");
  args_info->pruning_orig = NULL;
  args_info->methodPreconditionsInSeparateLeafs_flag = 0;
  args_info->optimisation_flag = 1;
  args_info->downward_arg = gengetopt_strdup ("none");
  args_info->downward_orig = NULL;
  args_info->downwardConf_arg = gengetopt_strdup ("ehc-ff()");
  args_info->downwardConf_orig = NULL;
  args_info->transtype_arg = gengetopt_strdup ("push");
  args_info->transtype_orig = NULL;
  args_info->forceTransType_flag = 0;
  args_info->sasfile_arg = gengetopt_strdup ("output.sas");
  args_info->sasfile_orig = NULL;
  args_info->pgb_arg = 0;
  args_info->pgb_orig = NULL;
  args_info->pgbsteps_arg = 1;
  args_info->pgbsteps_orig = NULL;
  args_info->onlyGenerate_flag = 0;
  args_info->iterate_flag = 0;
  args_info->realCosts_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{


  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->debug_help = gengetopt_args_info_help[3] ;
  args_info->seed_help = gengetopt_args_info_help[4] ;
  args_info->timelimit_help = gengetopt_args_info_help[5] ;
  args_info->noPlanOutput_help = gengetopt_args_info_help[6] ;
  args_info->writeInputToHDDL_help = gengetopt_args_info_help[7] ;
  args_info->heuristicHelp_help = gengetopt_args_info_help[8] ;
  args_info->progression_help = gengetopt_args_info_help[12] ;
  args_info->sat_help = gengetopt_args_info_help[13] ;
  args_info->bdd_help = gengetopt_args_info_help[14] ;
  args_info->translation_help = gengetopt_args_info_help[15] ;
  args_info->interactive_help = gengetopt_args_info_help[16] ;
  args_info->heuristic_help = gengetopt_args_info_help[18] ;
  args_info->heuristic_min = 0;
  args_info->heuristic_max = 0;
  args_info->astarweight_help = gengetopt_args_info_help[19] ;
  args_info->gValue_help = gengetopt_args_info_help[20] ;
  args_info->suboptimal_help = gengetopt_args_info_help[21] ;
  args_info->noVisitedList_help = gengetopt_args_info_help[24] ;
  args_info->noTaskHash_help = gengetopt_args_info_help[25] ;
  args_info->noTaskSequenceHash_help = gengetopt_args_info_help[26] ;
  args_info->noTopologicalOrdering_help = gengetopt_args_info_help[27] ;
  args_info->noLayers_help = gengetopt_args_info_help[28] ;
  args_info->noOrderPairs_help = gengetopt_args_info_help[29] ;
  args_info->noParallelSequences_help = gengetopt_args_info_help[30] ;
  args_info->noGIcheck_help = gengetopt_args_info_help[31] ;
  args_info->blockcompression_help = gengetopt_args_info_help[33] ;
  args_info->satmutexes_help = gengetopt_args_info_help[34] ;
  args_info->pruning_help = gengetopt_args_info_help[35] ;
  args_info->methodPreconditionsInSeparateLeafs_help = gengetopt_args_info_help[36] ;
  args_info->optimisation_help = gengetopt_args_info_help[37] ;
  args_info->downward_help = gengetopt_args_info_help[39] ;
  args_info->downwardConf_help = gengetopt_args_info_help[40] ;
  args_info->transtype_help = gengetopt_args_info_help[41] ;
  args_info->forceTransType_help = gengetopt_args_info_help[42] ;
  args_info->sasfile_help = gengetopt_args_info_help[43] ;
  args_info->pgb_help = gengetopt_args_info_help[44] ;
  args_info->pgbsteps_help = gengetopt_args_info_help[45] ;
  args_info->onlyGenerate_help = gengetopt_args_info_help[46] ;
  args_info->iterate_help = gengetopt_args_info_help[47] ;
  args_info->realCosts_help = gengetopt_args_info_help[48] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);

  if (strlen(gengetopt_args_info_versiontext) > 0)
    printf("\n%s\n", gengetopt_args_info_versiontext);
}

static void print_help_common(void)
{
	size_t len_purpose = strlen(gengetopt_args_info_purpose);
	size_t len_usage = strlen(gengetopt_args_info_usage);

	if (len_usage > 0) {
		printf("%s\n", gengetopt_args_info_usage);
	}
	if (len_purpose > 0) {
		printf("%s\n", gengetopt_args_info_purpose);
	}

	if (len_usage || len_purpose) {
		printf("\n");
	}

	if (strlen(gengetopt_args_info_description) > 0) {
		printf("%s\n\n", gengetopt_args_info_description);
	}
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->seed_orig));
  free_string_field (&(args_info->timelimit_orig));
  free_multiple_string_field (args_info->heuristic_given, &(args_info->heuristic_arg), &(args_info->heuristic_orig));
  free_string_field (&(args_info->astarweight_orig));
  free_string_field (&(args_info->gValue_arg));
  free_string_field (&(args_info->gValue_orig));
  free_string_field (&(args_info->pruning_arg));
  free_string_field (&(args_info->pruning_orig));
  free_string_field (&(args_info->downward_arg));
  free_string_field (&(args_info->downward_orig));
  free_string_field (&(args_info->downwardConf_arg));
  free_string_field (&(args_info->downwardConf_orig));
  free_string_field (&(args_info->transtype_arg));
  free_string_field (&(args_info->transtype_orig));
  free_string_field (&(args_info->sasfile_arg));
  free_string_field (&(args_info->sasfile_orig));
  free_string_field (&(args_info->pgb_orig));
  free_string_field (&(args_info->pgbsteps_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->debug_given)
    write_into_file(outfile, "debug", 0, 0 );
  if (args_info->seed_given)
    write_into_file(outfile, "seed", args_info->seed_orig, 0);
  if (args_info->timelimit_given)
    write_into_file(outfile, "timelimit", args_info->timelimit_orig, 0);
  if (args_info->noPlanOutput_given)
    write_into_file(outfile, "noPlanOutput", 0, 0 );
  if (args_info->writeInputToHDDL_given)
    write_into_file(outfile, "writeInputToHDDL", 0, 0 );
  if (args_info->heuristicHelp_given)
    write_into_file(outfile, "heuristicHelp", 0, 0 );
  if (args_info->progression_given)
    write_into_file(outfile, "progression", 0, 0 );
  if (args_info->sat_given)
    write_into_file(outfile, "sat", 0, 0 );
  if (args_info->bdd_given)
    write_into_file(outfile, "bdd", 0, 0 );
  if (args_info->translation_given)
    write_into_file(outfile, "translation", 0, 0 );
  if (args_info->interactive_given)
    write_into_file(outfile, "interactive", 0, 0 );
  write_multiple_into_file(outfile, args_info->heuristic_given, "heuristic", args_info->heuristic_orig, 0);
  if (args_info->astarweight_given)
    write_into_file(outfile, "astarweight", args_info->astarweight_orig, 0);
  if (args_info->gValue_given)
    write_into_file(outfile, "gValue", args_info->gValue_orig, cmdline_parser_gValue_values);
  if (args_info->suboptimal_given)
    write_into_file(outfile, "suboptimal", 0, 0 );
  if (args_info->noVisitedList_given)
    write_into_file(outfile, "noVisitedList", 0, 0 );
  if (args_info->noTaskHash_given)
    write_into_file(outfile, "noTaskHash", 0, 0 );
  if (args_info->noTaskSequenceHash_given)
    write_into_file(outfile, "noTaskSequenceHash", 0, 0 );
  if (args_info->noTopologicalOrdering_given)
    write_into_file(outfile, "noTopologicalOrdering", 0, 0 );
  if (args_info->noLayers_given)
    write_into_file(outfile, "noLayers", 0, 0 );
  if (args_info->noOrderPairs_given)
    write_into_file(outfile, "noOrderPairs", 0, 0 );
  if (args_info->noParallelSequences_given)
    write_into_file(outfile, "noParallelSequences", 0, 0 );
  if (args_info->noGIcheck_given)
    write_into_file(outfile, "noGIcheck", 0, 0 );
  if (args_info->blockcompression_given)
    write_into_file(outfile, "blockcompression", 0, 0 );
  if (args_info->satmutexes_given)
    write_into_file(outfile, "satmutexes", 0, 0 );
  if (args_info->pruning_given)
    write_into_file(outfile, "pruning", args_info->pruning_orig, cmdline_parser_pruning_values);
  if (args_info->methodPreconditionsInSeparateLeafs_given)
    write_into_file(outfile, "methodPreconditionsInSeparateLeafs", 0, 0 );
  if (args_info->optimisation_given)
    write_into_file(outfile, "optimisation", 0, 0 );
  if (args_info->downward_given)
    write_into_file(outfile, "downward", args_info->downward_orig, 0);
  if (args_info->downwardConf_given)
    write_into_file(outfile, "downwardConf", args_info->downwardConf_orig, 0);
  if (args_info->transtype_given)
    write_into_file(outfile, "transtype", args_info->transtype_orig, cmdline_parser_transtype_values);
  if (args_info->forceTransType_given)
    write_into_file(outfile, "forceTransType", 0, 0 );
  if (args_info->sasfile_given)
    write_into_file(outfile, "sasfile", args_info->sasfile_orig, 0);
  if (args_info->pgb_given)
    write_into_file(outfile, "pgb", args_info->pgb_orig, 0);
  if (args_info->pgbsteps_given)
    write_into_file(outfile, "pgbsteps", args_info->pgbsteps_orig, 0);
  if (args_info->onlyGenerate_given)
    write_into_file(outfile, "onlyGenerate", 0, 0 );
  if (args_info->iterate_given)
    write_into_file(outfile, "iterate", 0, 0 );
  if (args_info->realCosts_given)
    write_into_file(outfile, "realCosts", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
static void
reset_group_planningAlgorithm(struct gengetopt_args_info *args_info)
{
  if (! args_info->planningAlgorithm_group_counter)
    return;
  
  args_info->progression_given = 0 ;
  args_info->sat_given = 0 ;
  args_info->bdd_given = 0 ;
  args_info->translation_given = 0 ;
  args_info->interactive_given = 0 ;

  args_info->planningAlgorithm_group_counter = 0;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->heuristic_given, args_info->heuristic_min, args_info->heuristic_max, "'--heuristic' ('-H')"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}

/*
 * Extracted from the glibc source tree, version 2.3.6
 *
 * Licensed under the GPL as per the whole glibc source tree.
 *
 * This file was modified so that getopt_long can be called
 * many times without risking previous memory to be spoiled.
 *
 * Modified by Andre Noll and Lorenzo Bettini for use in
 * GNU gengetopt generated files.
 *
 */

/* 
 * we must include anything we need since this file is not thought to be
 * inserted in a file already using getopt.h
 *
 * Lorenzo
 */

struct option
{
  const char *name;
  /* has_arg can't be an enum because some compilers complain about
     type mismatches in all the code that assumes it is an int.  */
  int has_arg;
  int *flag;
  int val;
};

/* This version of `getopt' appears to the caller like standard Unix `getopt'
   but it behaves differently for the user, since it allows the user
   to intersperse the options with the other arguments.

   As `getopt' works, it permutes the elements of ARGV so that,
   when it is done, all the options precede everything else.  Thus
   all application programs are extended to handle flexible argument order.
*/
/*
   If the field `flag' is not NULL, it points to a variable that is set
   to the value given in the field `val' when the option is found, but
   left unchanged if the option is not found.

   To have a long-named option do something other than set an `int' to
   a compiled-in constant, such as set a value from `custom_optarg', set the
   option's `flag' field to zero and its `val' field to a nonzero
   value (the equivalent single-letter option character, if there is
   one).  For long options that have a zero `flag' field, `getopt'
   returns the contents of the `val' field.  */

/* Names for the values of the `has_arg' field of `struct option'.  */
#ifndef no_argument
#define no_argument		0
#endif

#ifndef required_argument
#define required_argument	1
#endif

#ifndef optional_argument
#define optional_argument	2
#endif

struct custom_getopt_data {
	/*
	 * These have exactly the same meaning as the corresponding global variables,
	 * except that they are used for the reentrant versions of getopt.
	 */
	int custom_optind;
	int custom_opterr;
	int custom_optopt;
	char *custom_optarg;

	/* True if the internal members have been initialized.  */
	int initialized;

	/*
	 * The next char to be scanned in the option-element in which the last option
	 * character we returned was found.  This allows us to pick up the scan where
	 * we left off.  If this is zero, or a null string, it means resume the scan by
	 * advancing to the next ARGV-element.
	 */
	char *nextchar;

	/*
	 * Describe the part of ARGV that contains non-options that have been skipped.
	 * `first_nonopt' is the index in ARGV of the first of them; `last_nonopt' is
	 * the index after the last of them.
	 */
	int first_nonopt;
	int last_nonopt;
};

/*
 * the variables optarg, optind, opterr and optopt are renamed with
 * the custom_ prefix so that they don't interfere with getopt ones.
 *
 * Moreover they're static so they are visible only from within the
 * file where this very file will be included.
 */

/*
 * For communication from `custom_getopt' to the caller.  When `custom_getopt' finds an
 * option that takes an argument, the argument value is returned here.
 */
static char *custom_optarg;

/*
 * Index in ARGV of the next element to be scanned.  This is used for
 * communication to and from the caller and for communication between
 * successive calls to `custom_getopt'.
 *
 * On entry to `custom_getopt', 1 means this is the first call; initialize.
 *
 * When `custom_getopt' returns -1, this is the index of the first of the non-option
 * elements that the caller should itself scan.
 *
 * Otherwise, `custom_optind' communicates from one call to the next how much of ARGV
 * has been scanned so far.
 *
 * 1003.2 says this must be 1 before any call.
 */
static int custom_optind = 1;

/*
 * Callers store zero here to inhibit the error message for unrecognized
 * options.
 */
static int custom_opterr = 1;

/*
 * Set to an option character which was unrecognized.  This must be initialized
 * on some systems to avoid linking in the system's own getopt implementation.
 */
static int custom_optopt = '?';

/*
 * Exchange two adjacent subsequences of ARGV.  One subsequence is elements
 * [first_nonopt,last_nonopt) which contains all the non-options that have been
 * skipped so far.  The other is elements [last_nonopt,custom_optind), which contains
 * all the options processed since those non-options were skipped.
 * `first_nonopt' and `last_nonopt' are relocated so that they describe the new
 * indices of the non-options in ARGV after they are moved.
 */
static void exchange(char **argv, struct custom_getopt_data *d)
{
	int bottom = d->first_nonopt;
	int middle = d->last_nonopt;
	int top = d->custom_optind;
	char *tem;

	/*
	 * Exchange the shorter segment with the far end of the longer segment.
	 * That puts the shorter segment into the right place.  It leaves the
	 * longer segment in the right place overall, but it consists of two
	 * parts that need to be swapped next.
	 */
	while (top > middle && middle > bottom) {
		if (top - middle > middle - bottom) {
			/* Bottom segment is the short one.  */
			int len = middle - bottom;
			int i;

			/* Swap it with the top part of the top segment.  */
			for (i = 0; i < len; i++) {
				tem = argv[bottom + i];
				argv[bottom + i] =
					argv[top - (middle - bottom) + i];
				argv[top - (middle - bottom) + i] = tem;
			}
			/* Exclude the moved bottom segment from further swapping.  */
			top -= len;
		} else {
			/* Top segment is the short one.  */
			int len = top - middle;
			int i;

			/* Swap it with the bottom part of the bottom segment.  */
			for (i = 0; i < len; i++) {
				tem = argv[bottom + i];
				argv[bottom + i] = argv[middle + i];
				argv[middle + i] = tem;
			}
			/* Exclude the moved top segment from further swapping.  */
			bottom += len;
		}
	}
	/* Update records for the slots the non-options now occupy.  */
	d->first_nonopt += (d->custom_optind - d->last_nonopt);
	d->last_nonopt = d->custom_optind;
}

/* Initialize the internal data when the first call is made.  */
static void custom_getopt_initialize(struct custom_getopt_data *d)
{
	/*
	 * Start processing options with ARGV-element 1 (since ARGV-element 0
	 * is the program name); the sequence of previously skipped non-option
	 * ARGV-elements is empty.
	 */
	d->first_nonopt = d->last_nonopt = d->custom_optind;
	d->nextchar = NULL;
	d->initialized = 1;
}

#define NONOPTION_P (argv[d->custom_optind][0] != '-' || argv[d->custom_optind][1] == '\0')

/* return: zero: continue, nonzero: return given value to user */
static int shuffle_argv(int argc, char *const *argv,const struct option *longopts,
	struct custom_getopt_data *d)
{
	/*
	 * Give FIRST_NONOPT & LAST_NONOPT rational values if CUSTOM_OPTIND has been
	 * moved back by the user (who may also have changed the arguments).
	 */
	if (d->last_nonopt > d->custom_optind)
		d->last_nonopt = d->custom_optind;
	if (d->first_nonopt > d->custom_optind)
		d->first_nonopt = d->custom_optind;
	/*
	 * If we have just processed some options following some
	 * non-options, exchange them so that the options come first.
	 */
	if (d->first_nonopt != d->last_nonopt &&
			d->last_nonopt != d->custom_optind)
		exchange((char **) argv, d);
	else if (d->last_nonopt != d->custom_optind)
		d->first_nonopt = d->custom_optind;
	/*
	 * Skip any additional non-options and extend the range of
	 * non-options previously skipped.
	 */
	while (d->custom_optind < argc && NONOPTION_P)
		d->custom_optind++;
	d->last_nonopt = d->custom_optind;
	/*
	 * The special ARGV-element `--' means premature end of options.  Skip
	 * it like a null option, then exchange with previous non-options as if
	 * it were an option, then skip everything else like a non-option.
	 */
	if (d->custom_optind != argc && !strcmp(argv[d->custom_optind], "--")) {
		d->custom_optind++;
		if (d->first_nonopt != d->last_nonopt
				&& d->last_nonopt != d->custom_optind)
			exchange((char **) argv, d);
		else if (d->first_nonopt == d->last_nonopt)
			d->first_nonopt = d->custom_optind;
		d->last_nonopt = argc;
		d->custom_optind = argc;
	}
	/*
	 * If we have done all the ARGV-elements, stop the scan and back over
	 * any non-options that we skipped and permuted.
	 */
	if (d->custom_optind == argc) {
		/*
		 * Set the next-arg-index to point at the non-options that we
		 * previously skipped, so the caller will digest them.
		 */
		if (d->first_nonopt != d->last_nonopt)
			d->custom_optind = d->first_nonopt;
		return -1;
	}
	/*
	 * If we have come to a non-option and did not permute it, either stop
	 * the scan or describe it to the caller and pass it by.
	 */
	if (NONOPTION_P) {
		d->custom_optarg = argv[d->custom_optind++];
		return 1;
	}
	/*
	 * We have found another option-ARGV-element. Skip the initial
	 * punctuation.
	 */
	d->nextchar = (argv[d->custom_optind] + 1 + (longopts != NULL && argv[d->custom_optind][1] == '-'));
	return 0;
}

/*
 * Check whether the ARGV-element is a long option.
 *
 * If there's a long option "fubar" and the ARGV-element is "-fu", consider
 * that an abbreviation of the long option, just like "--fu", and not "-f" with
 * arg "u".
 *
 * This distinction seems to be the most useful approach.
 *
 */
static int check_long_opt(int argc, char *const *argv, const char *optstring,
		const struct option *longopts, int *longind,
		int print_errors, struct custom_getopt_data *d)
{
	char *nameend;
	const struct option *p;
	const struct option *pfound = NULL;
	int exact = 0;
	int ambig = 0;
	int indfound = -1;
	int option_index;

	for (nameend = d->nextchar; *nameend && *nameend != '='; nameend++)
		/* Do nothing.  */ ;

	/* Test all long options for either exact match or abbreviated matches */
	for (p = longopts, option_index = 0; p->name; p++, option_index++)
		if (!strncmp(p->name, d->nextchar, nameend - d->nextchar)) {
			if ((unsigned int) (nameend - d->nextchar)
					== (unsigned int) strlen(p->name)) {
				/* Exact match found.  */
				pfound = p;
				indfound = option_index;
				exact = 1;
				break;
			} else if (pfound == NULL) {
				/* First nonexact match found.  */
				pfound = p;
				indfound = option_index;
			} else if (pfound->has_arg != p->has_arg
					|| pfound->flag != p->flag
					|| pfound->val != p->val)
				/* Second or later nonexact match found.  */
				ambig = 1;
		}
	if (ambig && !exact) {
		if (print_errors) {
			fprintf(stderr,
				"%s: option `%s' is ambiguous\n",
				argv[0], argv[d->custom_optind]);
		}
		d->nextchar += strlen(d->nextchar);
		d->custom_optind++;
		d->custom_optopt = 0;
		return '?';
	}
	if (pfound) {
		option_index = indfound;
		d->custom_optind++;
		if (*nameend) {
			if (pfound->has_arg != no_argument)
				d->custom_optarg = nameend + 1;
			else {
				if (print_errors) {
					if (argv[d->custom_optind - 1][1] == '-') {
						/* --option */
						fprintf(stderr, "%s: option `--%s' doesn't allow an argument\n",
							argv[0], pfound->name);
					} else {
						/* +option or -option */
						fprintf(stderr, "%s: option `%c%s' doesn't allow an argument\n",
							argv[0], argv[d->custom_optind - 1][0], pfound->name);
					}

				}
				d->nextchar += strlen(d->nextchar);
				d->custom_optopt = pfound->val;
				return '?';
			}
		} else if (pfound->has_arg == required_argument) {
			if (d->custom_optind < argc)
				d->custom_optarg = argv[d->custom_optind++];
			else {
				if (print_errors) {
					fprintf(stderr,
						"%s: option `%s' requires an argument\n",
						argv[0],
						argv[d->custom_optind - 1]);
				}
				d->nextchar += strlen(d->nextchar);
				d->custom_optopt = pfound->val;
				return optstring[0] == ':' ? ':' : '?';
			}
		}
		d->nextchar += strlen(d->nextchar);
		if (longind != NULL)
			*longind = option_index;
		if (pfound->flag) {
			*(pfound->flag) = pfound->val;
			return 0;
		}
		return pfound->val;
	}
	/*
	 * Can't find it as a long option.  If this is not getopt_long_only, or
	 * the option starts with '--' or is not a valid short option, then
	 * it's an error.  Otherwise interpret it as a short option.
	 */
	if (print_errors) {
		if (argv[d->custom_optind][1] == '-') {
			/* --option */
			fprintf(stderr,
				"%s: unrecognized option `--%s'\n",
				argv[0], d->nextchar);
		} else {
			/* +option or -option */
			fprintf(stderr,
				"%s: unrecognized option `%c%s'\n",
				argv[0], argv[d->custom_optind][0],
				d->nextchar);
		}
	}
	d->nextchar = (char *) "";
	d->custom_optind++;
	d->custom_optopt = 0;
	return '?';
}

static int check_short_opt(int argc, char *const *argv, const char *optstring,
		int print_errors, struct custom_getopt_data *d)
{
	char c = *d->nextchar++;
	const char *temp = strchr(optstring, c);

	/* Increment `custom_optind' when we start to process its last character.  */
	if (*d->nextchar == '\0')
		++d->custom_optind;
	if (!temp || c == ':') {
		if (print_errors)
			fprintf(stderr, "%s: invalid option -- %c\n", argv[0], c);

		d->custom_optopt = c;
		return '?';
	}
	if (temp[1] == ':') {
		if (temp[2] == ':') {
			/* This is an option that accepts an argument optionally.  */
			if (*d->nextchar != '\0') {
				d->custom_optarg = d->nextchar;
				d->custom_optind++;
			} else
				d->custom_optarg = NULL;
			d->nextchar = NULL;
		} else {
			/* This is an option that requires an argument.  */
			if (*d->nextchar != '\0') {
				d->custom_optarg = d->nextchar;
				/*
				 * If we end this ARGV-element by taking the
				 * rest as an arg, we must advance to the next
				 * element now.
				 */
				d->custom_optind++;
			} else if (d->custom_optind == argc) {
				if (print_errors) {
					fprintf(stderr,
						"%s: option requires an argument -- %c\n",
						argv[0], c);
				}
				d->custom_optopt = c;
				if (optstring[0] == ':')
					c = ':';
				else
					c = '?';
			} else
				/*
				 * We already incremented `custom_optind' once;
				 * increment it again when taking next ARGV-elt
				 * as argument.
				 */
				d->custom_optarg = argv[d->custom_optind++];
			d->nextchar = NULL;
		}
	}
	return c;
}

/*
 * Scan elements of ARGV for option characters given in OPTSTRING.
 *
 * If an element of ARGV starts with '-', and is not exactly "-" or "--",
 * then it is an option element.  The characters of this element
 * (aside from the initial '-') are option characters.  If `getopt'
 * is called repeatedly, it returns successively each of the option characters
 * from each of the option elements.
 *
 * If `getopt' finds another option character, it returns that character,
 * updating `custom_optind' and `nextchar' so that the next call to `getopt' can
 * resume the scan with the following option character or ARGV-element.
 *
 * If there are no more option characters, `getopt' returns -1.
 * Then `custom_optind' is the index in ARGV of the first ARGV-element
 * that is not an option.  (The ARGV-elements have been permuted
 * so that those that are not options now come last.)
 *
 * OPTSTRING is a string containing the legitimate option characters.
 * If an option character is seen that is not listed in OPTSTRING,
 * return '?' after printing an error message.  If you set `custom_opterr' to
 * zero, the error message is suppressed but we still return '?'.
 *
 * If a char in OPTSTRING is followed by a colon, that means it wants an arg,
 * so the following text in the same ARGV-element, or the text of the following
 * ARGV-element, is returned in `custom_optarg'.  Two colons mean an option that
 * wants an optional arg; if there is text in the current ARGV-element,
 * it is returned in `custom_optarg', otherwise `custom_optarg' is set to zero.
 *
 * If OPTSTRING starts with `-' or `+', it requests different methods of
 * handling the non-option ARGV-elements.
 * See the comments about RETURN_IN_ORDER and REQUIRE_ORDER, above.
 *
 * Long-named options begin with `--' instead of `-'.
 * Their names may be abbreviated as long as the abbreviation is unique
 * or is an exact match for some defined option.  If they have an
 * argument, it follows the option name in the same ARGV-element, separated
 * from the option name by a `=', or else the in next ARGV-element.
 * When `getopt' finds a long-named option, it returns 0 if that option's
 * `flag' field is nonzero, the value of the option's `val' field
 * if the `flag' field is zero.
 *
 * The elements of ARGV aren't really const, because we permute them.
 * But we pretend they're const in the prototype to be compatible
 * with other systems.
 *
 * LONGOPTS is a vector of `struct option' terminated by an
 * element containing a name which is zero.
 *
 * LONGIND returns the index in LONGOPT of the long-named option found.
 * It is only valid when a long-named option has been found by the most
 * recent call.
 *
 * Return the option character from OPTS just read.  Return -1 when there are
 * no more options.  For unrecognized options, or options missing arguments,
 * `custom_optopt' is set to the option letter, and '?' is returned.
 *
 * The OPTS string is a list of characters which are recognized option letters,
 * optionally followed by colons, specifying that that letter takes an
 * argument, to be placed in `custom_optarg'.
 *
 * If a letter in OPTS is followed by two colons, its argument is optional.
 * This behavior is specific to the GNU `getopt'.
 *
 * The argument `--' causes premature termination of argument scanning,
 * explicitly telling `getopt' that there are no more options.  If OPTS begins
 * with `--', then non-option arguments are treated as arguments to the option
 * '\0'.  This behavior is specific to the GNU `getopt'.
 */

static int getopt_internal_r(int argc, char *const *argv, const char *optstring,
		const struct option *longopts, int *longind,
		struct custom_getopt_data *d)
{
	int ret, print_errors = d->custom_opterr;

	if (optstring[0] == ':')
		print_errors = 0;
	if (argc < 1)
		return -1;
	d->custom_optarg = NULL;

	/* 
	 * This is a big difference with GNU getopt, since optind == 0
	 * means initialization while here 1 means first call.
	 */
	if (d->custom_optind == 0 || !d->initialized) {
		if (d->custom_optind == 0)
			d->custom_optind = 1;	/* Don't scan ARGV[0], the program name.  */
		custom_getopt_initialize(d);
	}
	if (d->nextchar == NULL || *d->nextchar == '\0') {
		ret = shuffle_argv(argc, argv, longopts, d);
		if (ret)
			return ret;
	}
	if (longopts && (argv[d->custom_optind][1] == '-' ))
		return check_long_opt(argc, argv, optstring, longopts,
			longind, print_errors, d);
	return check_short_opt(argc, argv, optstring, print_errors, d);
}

static int custom_getopt_internal(int argc, char *const *argv, const char *optstring,
	const struct option *longopts, int *longind)
{
	int result;
	/* Keep a global copy of all internal members of d */
	static struct custom_getopt_data d;

	d.custom_optind = custom_optind;
	d.custom_opterr = custom_opterr;
	result = getopt_internal_r(argc, argv, optstring, longopts,
		longind, &d);
	custom_optind = d.custom_optind;
	custom_optarg = d.custom_optarg;
	custom_optopt = d.custom_optopt;
	return result;
}

static int custom_getopt_long (int argc, char *const *argv, const char *options,
	const struct option *long_options, int *opt_index)
{
	return custom_getopt_internal(argc, argv, options, long_options,
		opt_index);
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  union generic_value multiple_default_value;

  struct generic_list * heuristic_list = NULL;
  int error_occurred = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;

  char *optarg;
  int optind;
  int opterr;
  int optopt;
  
  package_name = argv[0];
  
  /* TODO: Why is this here? It is not used anywhere. */
  override = params->override;
  FIX_UNUSED(override);

  initialize = params->initialize;
  check_required = params->check_required;

  /* TODO: Why is this here? It is not used anywhere. */
  check_ambiguity = params->check_ambiguity;
  FIX_UNUSED(check_ambiguity);

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 0 },
        { "debug",	0, NULL, 'd' },
        { "seed",	1, NULL, 'S' },
        { "timelimit",	1, NULL, 't' },
        { "noPlanOutput",	0, NULL, 'N' },
        { "writeInputToHDDL",	0, NULL, 0 },
        { "heuristicHelp",	0, NULL, 0 },
        { "progression",	0, NULL, 'p' },
        { "sat",	0, NULL, 's' },
        { "bdd",	0, NULL, 'b' },
        { "translation",	0, NULL, '2' },
        { "interactive",	0, NULL, 'I' },
        { "heuristic",	1, NULL, 'H' },
        { "astarweight",	1, NULL, 'w' },
        { "gValue",	1, NULL, 'g' },
        { "suboptimal",	0, NULL, 0 },
        { "noVisitedList",	0, NULL, 'V' },
        { "noTaskHash",	0, NULL, 'T' },
        { "noTaskSequenceHash",	0, NULL, 'Q' },
        { "noTopologicalOrdering",	0, NULL, 'O' },
        { "noLayers",	0, NULL, 0 },
        { "noOrderPairs",	0, NULL, 0 },
        { "noParallelSequences",	0, NULL, 0 },
        { "noGIcheck",	0, NULL, 0 },
        { "blockcompression",	0, NULL, 'B' },
        { "satmutexes",	0, NULL, 'M' },
        { "pruning",	1, NULL, 'P' },
        { "methodPreconditionsInSeparateLeafs",	0, NULL, 'm' },
        { "optimisation",	0, NULL, 'o' },
        { "downward",	1, NULL, 0 },
        { "downwardConf",	1, NULL, 0 },
        { "transtype",	1, NULL, 0 },
        { "forceTransType",	0, NULL, 0 },
        { "sasfile",	1, NULL, 0 },
        { "pgb",	1, NULL, 0 },
        { "pgbsteps",	1, NULL, 0 },
        { "onlyGenerate",	0, NULL, 0 },
        { "iterate",	0, NULL, 0 },
        { "realCosts",	0, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      custom_optarg = optarg;
      custom_optind = optind;
      custom_opterr = opterr;
      custom_optopt = optopt;

      c = custom_getopt_long (argc, argv, "hdS:t:Npsb2IH:w:g:VTQOBMP:mo", long_options, &option_index);

      optarg = custom_optarg;
      optind = custom_optind;
      opterr = custom_opterr;
      optopt = custom_optopt;

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'd':	/* activate debug mode.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->debug_given),
              &(local_args_info.debug_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "debug", 'd',
              additional_error))
            goto failure;
        
          break;
        case 'S':	/* specify the random seed.  */
        
        
          if (update_arg( (void *)&(args_info->seed_arg), 
               &(args_info->seed_orig), &(args_info->seed_given),
              &(local_args_info.seed_given), optarg, 0, "42", ARG_INT,
              check_ambiguity, override, 0, 0,
              "seed", 'S',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* specify timelimit in seconds.  */
        
        
          if (update_arg( (void *)&(args_info->timelimit_arg), 
               &(args_info->timelimit_orig), &(args_info->timelimit_given),
              &(local_args_info.timelimit_given), optarg, 0, "1800", ARG_INT,
              check_ambiguity, override, 0, 0,
              "timelimit", 't',
              additional_error))
            goto failure;
        
          break;
        case 'N':	/* don't output the plan [default=print plan].  */
        
        
          if (update_arg((void *)&(args_info->noPlanOutput_flag), 0, &(args_info->noPlanOutput_given),
              &(local_args_info.noPlanOutput_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "noPlanOutput", 'N',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* progression search.  */
        
          if (args_info->planningAlgorithm_group_counter && override)
            reset_group_planningAlgorithm (args_info);
          args_info->planningAlgorithm_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->progression_given),
              &(local_args_info.progression_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "progression", 'p',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* translation to SAT.  */
        
          if (args_info->planningAlgorithm_group_counter && override)
            reset_group_planningAlgorithm (args_info);
          args_info->planningAlgorithm_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->sat_given),
              &(local_args_info.sat_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "sat", 's',
              additional_error))
            goto failure;
        
          break;
        case 'b':	/* symbolic search.  */
        
          if (args_info->planningAlgorithm_group_counter && override)
            reset_group_planningAlgorithm (args_info);
          args_info->planningAlgorithm_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->bdd_given),
              &(local_args_info.bdd_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "bdd", 'b',
              additional_error))
            goto failure;
        
          break;
        case '2':	/* translation-based planner.  */
        
          if (args_info->planningAlgorithm_group_counter && override)
            reset_group_planningAlgorithm (args_info);
          args_info->planningAlgorithm_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->translation_given),
              &(local_args_info.translation_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "translation", '2',
              additional_error))
            goto failure;
        
          break;
        case 'I':	/* interactive search.  */
        
          if (args_info->planningAlgorithm_group_counter && override)
            reset_group_planningAlgorithm (args_info);
          args_info->planningAlgorithm_group_counter += 1;
        
          if (update_arg( 0 , 
               0 , &(args_info->interactive_given),
              &(local_args_info.interactive_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "interactive", 'I',
              additional_error))
            goto failure;
        
          break;
        case 'H':	/* specify heuristics. If you want to know how to specify a heuristic, use --heuristicHelp. The first heuristic in the list is the one used for search. Starting from the second, all other heuristics are used as tie-breakers. If you specify the same heuristic twice, it will only be computed once. If all tie-breakers are equal, a random number selected per search node is used as the final tie-breaker..  */
        
          if (update_multiple_arg_temp(&heuristic_list, 
              &(local_args_info.heuristic_given), optarg, 0, "rc2(ff)", ARG_STRING,
              "heuristic", 'H',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* weight of the heuristic for weighted A* (also called greedy-A*). The default is 1, which yields the standard A* algorithm..  */
        
        
          if (update_arg( (void *)&(args_info->astarweight_arg), 
               &(args_info->astarweight_orig), &(args_info->astarweight_given),
              &(local_args_info.astarweight_given), optarg, 0, "1", ARG_INT,
              check_ambiguity, override, 0, 0,
              "astarweight", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* g value. You can select
        path: one for each applied action and performed decomposition
        mixed: summed cost of the applied actions plus 1 for every applied decomposition
        action: summed cost of the applied actions
        none: constant zero.
.  */
        
        
          if (update_arg( (void *)&(args_info->gValue_arg), 
               &(args_info->gValue_orig), &(args_info->gValue_given),
              &(local_args_info.gValue_given), optarg, cmdline_parser_gValue_values, "path", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "gValue", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'V':	/* disable visited lists [default=with lists].  */
        
        
          if (update_arg((void *)&(args_info->noVisitedList_flag), 0, &(args_info->noVisitedList_given),
              &(local_args_info.noVisitedList_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "noVisitedList", 'V',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* disable task hashing [default=with task hash].  */
        
        
          if (update_arg((void *)&(args_info->noTaskHash_flag), 0, &(args_info->noTaskHash_given),
              &(local_args_info.noTaskHash_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "noTaskHash", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'Q':	/* disable task sequence hashing [default=with task sequence hash].  */
        
        
          if (update_arg((void *)&(args_info->noTaskSequenceHash_flag), 0, &(args_info->noTaskSequenceHash_given),
              &(local_args_info.noTaskSequenceHash_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "noTaskSequenceHash", 'Q',
              additional_error))
            goto failure;
        
          break;
        case 'O':	/* disable visited checking with task sequences, this makes totally-ordered visited lists incomplete [default=with order].  */
        
        
          if (update_arg((void *)&(args_info->noTopologicalOrdering_flag), 0, &(args_info->noTopologicalOrdering_given),
              &(local_args_info.noTopologicalOrdering_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "noTopologicalOrdering", 'O',
              additional_error))
            goto failure;
        
          break;
        case 'B':	/* apply block compression.  */
        
        
          if (update_arg((void *)&(args_info->blockcompression_flag), 0, &(args_info->blockcompression_given),
              &(local_args_info.blockcompression_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "blockcompression", 'B',
              additional_error))
            goto failure;
        
          break;
        case 'M':	/* encode SAT mutexes.  */
        
        
          if (update_arg((void *)&(args_info->satmutexes_flag), 0, &(args_info->satmutexes_given),
              &(local_args_info.satmutexes_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "satmutexes", 'M',
              additional_error))
            goto failure;
        
          break;
        case 'P':	/* pruning mode.  */
        
        
          if (update_arg( (void *)&(args_info->pruning_arg), 
               &(args_info->pruning_orig), &(args_info->pruning_given),
              &(local_args_info.pruning_given), optarg, cmdline_parser_pruning_values, "ff", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "pruning", 'P',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* if in partial order mode, put method precondition actions into extra leafs. This allows for better encoding of executability, but may increase the size of the PDT.  */
        
        
          if (update_arg((void *)&(args_info->methodPreconditionsInSeparateLeafs_flag), 0, &(args_info->methodPreconditionsInSeparateLeafs_given),
              &(local_args_info.methodPreconditionsInSeparateLeafs_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "methodPreconditionsInSeparateLeafs", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'o':	/* after finding the first plan, continue search to find plans of lower cost.  */
        
        
          if (update_arg((void *)&(args_info->optimisation_flag), 0, &(args_info->optimisation_given),
              &(local_args_info.optimisation_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "optimisation", 'o',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "version") == 0) {
            cmdline_parser_print_version ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* don't run the engine at all. Output the given SAS+ planning problem as HDDL again..  */
          if (strcmp (long_options[option_index].name, "writeInputToHDDL") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->writeInputToHDDL_flag), 0, &(args_info->writeInputToHDDL_given),
                &(local_args_info.writeInputToHDDL_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "writeInputToHDDL", '-',
                additional_error))
              goto failure;
          
          }
          /* will print the help page for the heuristics.  */
          else if (strcmp (long_options[option_index].name, "heuristicHelp") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->heuristicHelp_flag), 0, &(args_info->heuristicHelp_given),
                &(local_args_info.heuristicHelp_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "heuristicHelp", '-',
                additional_error))
              goto failure;
          
          }
          /* suboptimal search (early goal test and visited lists ignores costs).  */
          else if (strcmp (long_options[option_index].name, "suboptimal") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->suboptimal_flag), 0, &(args_info->suboptimal_given),
                &(local_args_info.suboptimal_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "suboptimal", '-',
                additional_error))
              goto failure;
          
          }
          /* disable layer hashing [default=with layer hash].  */
          else if (strcmp (long_options[option_index].name, "noLayers") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noLayers_flag), 0, &(args_info->noLayers_given),
                &(local_args_info.noLayers_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noLayers", '-',
                additional_error))
              goto failure;
          
          }
          /* disable order pairs hashing [default=with order pairs hash].  */
          else if (strcmp (long_options[option_index].name, "noOrderPairs") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noOrderPairs_flag), 0, &(args_info->noOrderPairs_given),
                &(local_args_info.noOrderPairs_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noOrderPairs", '-',
                additional_error))
              goto failure;
          
          }
          /* disable optimisation for parallel sequences [default=with optimisation].  */
          else if (strcmp (long_options[option_index].name, "noParallelSequences") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noParallelSequences_flag), 0, &(args_info->noParallelSequences_given),
                &(local_args_info.noParallelSequences_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noParallelSequences", '-',
                additional_error))
              goto failure;
          
          }
          /* disable GI-complete equivalence checking for partially ordered task networks [default=with GI-complete checking].  */
          else if (strcmp (long_options[option_index].name, "noGIcheck") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->noGIcheck_flag), 0, &(args_info->noGIcheck_given),
                &(local_args_info.noGIcheck_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "noGIcheck", '-',
                additional_error))
              goto failure;
          
          }
          /* path to fast downward executable.  */
          else if (strcmp (long_options[option_index].name, "downward") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->downward_arg), 
                 &(args_info->downward_orig), &(args_info->downward_given),
                &(local_args_info.downward_given), optarg, 0, "none", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "downward", '-',
                additional_error))
              goto failure;
          
          }
          /* configuration given to fast downward. This has two special values that are expanded to proper configurations. Use ehc-ff() for enforced hill climbing with FF and lazy-cea() for lazy-greedy search with the context enhanced additive heuristic..  */
          else if (strcmp (long_options[option_index].name, "downwardConf") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->downwardConf_arg), 
                 &(args_info->downwardConf_orig), &(args_info->downwardConf_given),
                &(local_args_info.downwardConf_given), optarg, 0, "ehc-ff()", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "downwardConf", '-',
                additional_error))
              goto failure;
          
          }
          /* type of translation to use.  */
          else if (strcmp (long_options[option_index].name, "transtype") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->transtype_arg), 
                 &(args_info->transtype_orig), &(args_info->transtype_given),
                &(local_args_info.transtype_given), optarg, cmdline_parser_transtype_values, "push", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "transtype", '-',
                additional_error))
              goto failure;
          
          }
          /* by default, pandaPIengine will switch to a getter encoding if it detects the prerequisites for it in the problem. This flag disables this behaviour and always uses the given encoding..  */
          else if (strcmp (long_options[option_index].name, "forceTransType") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->forceTransType_flag), 0, &(args_info->forceTransType_given),
                &(local_args_info.forceTransType_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "forceTransType", '-',
                additional_error))
              goto failure;
          
          }
          /* name of the SAS+ file generated. In planning mode this file will be written and used as a temporary file.  */
          else if (strcmp (long_options[option_index].name, "sasfile") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->sasfile_arg), 
                 &(args_info->sasfile_orig), &(args_info->sasfile_given),
                &(local_args_info.sasfile_given), optarg, 0, "output.sas", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "sasfile", '-',
                additional_error))
              goto failure;
          
          }
          /* the initial value of the progression bound. If zero, the minimum progression bound will be computed and used instead. This is the default behaviour!.  */
          else if (strcmp (long_options[option_index].name, "pgb") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->pgb_arg), 
                 &(args_info->pgb_orig), &(args_info->pgb_given),
                &(local_args_info.pgb_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "pgb", '-',
                additional_error))
              goto failure;
          
          }
          /* step size of the progression bound.  */
          else if (strcmp (long_options[option_index].name, "pgbsteps") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->pgbsteps_arg), 
                 &(args_info->pgbsteps_orig), &(args_info->pgbsteps_given),
                &(local_args_info.pgbsteps_given), optarg, 0, "1", ARG_INT,
                check_ambiguity, override, 0, 0,
                "pgbsteps", '-',
                additional_error))
              goto failure;
          
          }
          /* only generate the translation and don't solv it. This overrides also iterate.  */
          else if (strcmp (long_options[option_index].name, "onlyGenerate") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->onlyGenerate_flag), 0, &(args_info->onlyGenerate_given),
                &(local_args_info.onlyGenerate_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "onlyGenerate", '-',
                additional_error))
              goto failure;
          
          }
          /* if the initial pgb is unsolvable, increase by one and continue.  */
          else if (strcmp (long_options[option_index].name, "iterate") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->iterate_flag), 0, &(args_info->iterate_given),
                &(local_args_info.iterate_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "iterate", '-',
                additional_error))
              goto failure;
          
          }
          /* if enabled use the actual cost in the encoded model. Default is off, then all operators have unit cost..  */
          else if (strcmp (long_options[option_index].name, "realCosts") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->realCosts_flag), 0, &(args_info->realCosts_given),
                &(local_args_info.realCosts_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "realCosts", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */

  if (args_info->planningAlgorithm_group_counter > 1)
    {
      fprintf (stderr, "%s: %d options of group planningAlgorithm were given. At most one is required%s.\n", argv[0], args_info->planningAlgorithm_group_counter, (additional_error ? additional_error : ""));
      error_occurred = 1;
    }
  

  multiple_default_value.default_string_arg = "rc2(ff)";
  update_multiple_arg((void *)&(args_info->heuristic_arg),
    &(args_info->heuristic_orig), args_info->heuristic_given,
    local_args_info.heuristic_given, &multiple_default_value,
    ARG_STRING, heuristic_list);

  args_info->heuristic_given += local_args_info.heuristic_given;
  local_args_info.heuristic_given = 0;
  
  if (check_required)
    {
      error_occurred += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */


      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind++]) ;
    }

  return 0;

failure:
  free_list (heuristic_list, 1 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}

static unsigned int
cmdline_parser_create_argv(const char *cmdline_, char ***argv_ptr, const char *prog_name)
{
  char *cmdline, *p;
  size_t n = 0, j;
  int i;

  if (prog_name) {
    cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
    cmd_line_list_tmp->next = cmd_line_list;
    cmd_line_list = cmd_line_list_tmp;
    cmd_line_list->string_arg = gengetopt_strdup (prog_name);

    ++n;
  }

  cmdline = gengetopt_strdup(cmdline_);
  p = cmdline;

  while (p && strlen(p))
    {
      j = strcspn(p, " \t");
      ++n;
      if (j && j < strlen(p))
        {
          p[j] = '\0';

          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          p += (j+1);
          p += strspn(p, " \t");
        }
      else
        {
          cmd_line_list_tmp = (struct line_list *) malloc (sizeof (struct line_list));
          cmd_line_list_tmp->next = cmd_line_list;
          cmd_line_list = cmd_line_list_tmp;
          cmd_line_list->string_arg = gengetopt_strdup (p);

          break;
        }
    }

  *argv_ptr = (char **) malloc((n + 1) * sizeof(char *));
  cmd_line_list_tmp = cmd_line_list;
  for (i = (n-1); i >= 0; --i)
    {
      (*argv_ptr)[i] = cmd_line_list_tmp->string_arg;
      cmd_line_list_tmp = cmd_line_list_tmp->next;
    }

  (*argv_ptr)[n] = 0;

  free(cmdline);
  return n;
}

int
cmdline_parser_string(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name)
{
  return cmdline_parser_string2(cmdline, args_info, prog_name, 0, 1, 1);
}

int
cmdline_parser_string2(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name,
    int override, int initialize, int check_required)
{
  struct cmdline_parser_params params;

  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  return cmdline_parser_string_ext(cmdline, args_info, prog_name, &params);
}

int
cmdline_parser_string_ext(const char *cmdline, struct gengetopt_args_info *args_info, const char *prog_name,
    struct cmdline_parser_params *params)
{
  char **argv_ptr = 0;
  int result;
  unsigned int argc;
  
  argc = cmdline_parser_create_argv(cmdline, &argv_ptr, prog_name);
  
  result =
    cmdline_parser_internal (argc, argv_ptr, args_info, params, 0);
  
  if (argv_ptr)
    {
      free (argv_ptr);
    }

  free_cmd_list();
  
  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

/* vim: set ft=c noet ts=8 sts=8 sw=8 tw=80 nojs spell : */
